        
name: test
on:
  push: 
    branches: [main]

jobs:
  cicd-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v2
        
      - name: Configurar ambiente
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Iniciar banco
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.0
      
      - name: Executar pytest
        run: |
          cd user_crud
          pytest
